name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # main 브랜치에 푸시될 때 실행

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # 현재 사용 중인 pnpm 버전에 맞춰주세요

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Astro
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4